baseURL = "http://civilacademy.netlify.com/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Civil Academy Indonesia"
[markup.goldmark.renderer]
unsafe = true
